### ISSUE TITLE
V91.1 Issues/Bugs

### ISSUE THREAD

**Issue by adelando** [Ethenski/Civitas#1]
Hello,

Whilst testing the latest version i noticed a few things....

(In Plot settings)
Leaders of towns cannot see all plots claimed, only plots claimed by themselves.
Other members can also only see plots claimed by themselves too.
*Unsure if this is intentional or not.*

(In Civitas Settings / Global Settings / Day Length)
inputting 1440 is 24 Minutes but 86400 is 24 real hours, = Setting is in seconds instead of minutes
*Setting description states "1440 is 24 real hours"*

(Nations)
When a town is renamed and is also apart of a Nation, you cannot go into the Nation Editor (unclickable), Changing the name back works again.

(Wars)
No setting for Nation leaders to allow other towns to contribute to war fund,
Also no option for Nation leaders to grant permissions for other towns to manage war settings

Also the allies menu doesnt show Allied towns helping in the war.

**Comment by Ethenski** [comment]
All issues have been fixed in 0.95 (Except for plot issue, will work on that in a later update)
